package graph

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
)

func (g *InMemoryGraph) ExportWiki(outputDir string, commLabels map[int]string, communities map[string]int, centrality map[string]float64) error {
	if err := os.MkdirAll(outputDir, 0755); err != nil {
		return err
	}

	commMembers := make(map[int][]string)
	for id, cID := range communities {
		commMembers[cID] = append(commMembers[cID], id)
	}

	commIDs := make([]int, 0, len(commMembers))
	for cID := range commMembers {
		commIDs = append(commIDs, cID)
	}
	sort.Ints(commIDs)

	degTotal := make(map[string]int)
	for id := range g.Nodes {
		degTotal[id] = g.FanIn[id] + g.FanOut[id]
	}

	if err := g.writeWikiIndex(outputDir, commIDs, commMembers, commLabels, centrality, degTotal); err != nil {
		return err
	}

	for _, cID := range commIDs {
		if err := g.writeWikiCommunity(outputDir, cID, commMembers[cID], commLabels, communities, centrality, degTotal); err != nil {
			return err
		}
	}

	return nil
}

func (g *InMemoryGraph) writeWikiIndex(outputDir string, commIDs []int, commMembers map[int][]string, commLabels map[int]string, centrality map[string]float64, degTotal map[string]int) error {
	f, err := os.Create(filepath.Join(outputDir, "index.md"))
	if err != nil {
		return err
	}
	defer f.Close()

	fmt.Fprintf(f, "# sv-memory Knowledge Graph Wiki\n\n")
	fmt.Fprintf(f, "Total nodes: **%d** | Total edges: %d\n\n", len(g.Nodes), g.countEdges())

	var godNodes []struct {
		id    string
		deg   int
		label string
	}
	for id := range g.Nodes {
		d := degTotal[id]
		if d > 10 {
			godNodes = append(godNodes, struct {
				id    string
				deg   int
				label string
			}{id: id, deg: d, label: g.Nodes[id].Label})
		}
	}
	sort.Slice(godNodes, func(i, j int) bool { return godNodes[i].deg > godNodes[j].deg })
	if len(godNodes) > 10 {
		godNodes = godNodes[:10]
	}

	if len(godNodes) > 0 {
		fmt.Fprintf(f, "## God Nodes (Top Hubs)\n\n")
		fmt.Fprintf(f, "| Node | Degree |\n|---|---|\n")
		for _, gn := range godNodes {
			fmt.Fprintf(f, "| **%s** | %d |\n", gn.label, gn.deg)
		}
		fmt.Fprintf(f, "\n")
	}

	fmt.Fprintf(f, "## Communities\n\n")
	fmt.Fprintf(f, "| ID | Label | Size | Key Node |\n|---|---|---|---|\n")
	for _, cID := range commIDs {
		members := commMembers[cID]
		label := commLabels[cID]
		topNode := g.findTopNode(members, centrality)
		topLabel := ""
		if topNode != "" {
			if n, ok := g.Nodes[topNode]; ok {
				topLabel = n.Label
			}
		}
		fmt.Fprintf(f, "| %d | **%s** | %d | %s |\n", cID, label, len(members), topLabel)
	}
	fmt.Fprintf(f, "\n---\n*Generated by sv-memory*\n")
	return nil
}

func (g *InMemoryGraph) writeWikiCommunity(outputDir string, cID int, members []string, commLabels map[int]string, communities map[string]int, centrality map[string]float64, degTotal map[string]int) error {
	label := commLabels[cID]
	filename := fmt.Sprintf("community-%03d.md", cID)

	f, err := os.Create(filepath.Join(outputDir, filename))
	if err != nil {
		return err
	}
	defer f.Close()

	fmt.Fprintf(f, "# Community %d: %s\n\n", cID, label)
	fmt.Fprintf(f, "- **Size:** %d nodes\n", len(members))

	totalBC := 0.0
	for _, id := range members {
		totalBC += centrality[id]
	}
	avgBC := totalBC / float64(len(members))
	fmt.Fprintf(f, "- **Avg Betweenness Centrality:** %.2f\n", avgBC)

	sort.Slice(members, func(i, j int) bool {
		return degTotal[members[i]] > degTotal[members[j]]
	})

	fmt.Fprintf(f, "\n## Members\n\n")
	fmt.Fprintf(f, "| Node | Type | Fan-In | Fan-Out | BC | Degree |\n|---|---|---|---|---|---|\n")
	for _, id := range members {
		n := g.Nodes[id]
		fmt.Fprintf(f, "| **%s** | `%s` | %d | %d | %.2f | %d |\n",
			n.Label, n.Type, g.FanIn[id], g.FanOut[id], centrality[id], degTotal[id])
	}

	crossCommEdges := g.collectCrossCommunityEdges(cID, members, communities)
	if len(crossCommEdges) > 0 {
		fmt.Fprintf(f, "\n## Cross-Community Connections\n\n")
		fmt.Fprintf(f, "| Member | Connects To | Community | Relation |\n|---|---|---|---|\n")
		for _, ce := range crossCommEdges {
			fmt.Fprintf(f, "| **%s** | **%s** | %s | `%s` |\n",
				ce.sourceLabel, ce.targetLabel, ce.targetCommLabel, ce.relationType)
		}
	}
	fmt.Fprintf(f, "\n---\n*Generated by sv-memory*\n")
	return nil
}

type crossEdge struct {
	sourceLabel     string
	targetLabel     string
	targetCommLabel string
	relationType    string
}

func (g *InMemoryGraph) collectCrossCommunityEdges(cID int, members []string, communities map[string]int) []crossEdge {
	memberSet := make(map[string]bool, len(members))
	for _, id := range members {
		memberSet[id] = true
	}

	var result []crossEdge
	seen := make(map[string]bool)
	for _, srcID := range members {
		for _, edge := range g.EdgesBySource[srcID] {
			if memberSet[edge.TargetID] {
				continue
			}
			targetComm := communities[edge.TargetID]
			if targetComm == cID {
				continue
			}
			key := srcID + "->" + edge.TargetID
			if seen[key] {
				continue
			}
			seen[key] = true

			srcLabel := srcID
			if n, ok := g.Nodes[srcID]; ok {
				srcLabel = n.Label
			}
			tgtLabel := edge.TargetID
			if n, ok := g.Nodes[edge.TargetID]; ok {
				tgtLabel = n.Label
			}
			result = append(result, crossEdge{
				sourceLabel:     srcLabel,
				targetLabel:     tgtLabel,
				targetCommLabel: fmt.Sprintf("community_%d", targetComm),
				relationType:    edge.RelationType,
			})
		}
	}
	sort.Slice(result, func(i, j int) bool {
		return result[i].sourceLabel < result[j].sourceLabel
	})
	if len(result) > 20 {
		result = result[:20]
	}
	return result
}

func (g *InMemoryGraph) findTopNode(members []string, centrality map[string]float64) string {
	best := ""
	bestBC := -1.0
	for _, id := range members {
		if centrality[id] > bestBC {
			bestBC = centrality[id]
			best = id
		}
	}
	return best
}

func (g *InMemoryGraph) countEdges() int {
	seen := make(map[string]bool)
	count := 0
	for _, edges := range g.EdgesBySource {
		for _, e := range edges {
			key := e.SourceID + "->" + e.TargetID
			if !seen[key] {
				seen[key] = true
				count++
			}
		}
	}
	return count
}
